version: 0.0
os: linux
files:
  - source: target/index.html
    destination: /usr/share/tomcat/webapps/ROOT
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root
